# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('direccion', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=16)),
                ('estrellas', models.CharField(max_length=12)),
                ('url', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alojamiento_Seleccionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('alojamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Alojamiento')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('alojamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Alojamiento')),
            ],
        ),
        migrations.CreateModel(
            name='CSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=56)),
                ('titulo', models.CharField(max_length=56)),
                ('tamannoFuente', models.FloatField()),
                ('colorFondo', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('alojamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.Alojamiento')),
            ],
        ),
    ]
